- sc-memory/sc-store/sc_event.c
> [fix] Fix bug with sc_event for an empty ScAddr

- sc-memory/test/wrap/test_wrap.cpp
- sc-memory/test/wrap/units/test_codegen.cpp
- sc-memory/test/wrap/units/test_sc_agent.cpp
- sc-memory/test/wrap/units/test_sc_agent.hpp
> [test] Implement tests for ScAgent class

- sc-memory/cpp/sc_template.hpp
Implement first part of #212
```cpp
ScTemplateGenResult result;
....
for (size_t i = 0; i < result.size(); ++i)
{
ScAddr const addr = result[i];
...
}
```
```cpp
ScTemplateSearchResultItem item;
for (size_t i = 0; i < item.size(); ++i)
{
ScAddr const addr = item[i];
...
}
```
> Some work on #212

- CMakeLists.txt
- sc-kpm/CMakeLists.txt
- sc-kpm/iot/iotSpeech.cpp
- sc-kpm/nl/nlApiAi.cpp
- sc-kpm/nl/nlDialogue.cpp
- sc-kpm/nl/nlIvona.cpp
- sc-kpm/nl/nlKeynodes.cpp
- sc-kpm/nl/nlKeynodes.hpp
- sc-memory/cpp/kpm/sc_agent.cpp
- sc-memory/cpp/kpm/sc_agent.hpp
- sc-memory/cpp/sc_iterator.cpp
- sc-memory/cpp/sc_memory.cpp
- sc-memory/cpp/sc_stream.cpp
- sc-memory/cpp/sc_stream.hpp
- sc-memory/cpp/sc_wait.cpp
- sc-memory/cpp/sc_wait.hpp
- sc-memory/sc-store/sc_storage.c
- sc-memory/test/wrap/units/test_wait.cpp
> Some improvements

- docs/changelog.md
- docs/dev/pr.md
- docs/dev/test.md
- mkdocs.yml
- sc-memory/cpp/CMakeLists.txt
- sc-memory/cpp/utils/sc_test.cpp
- sc-memory/cpp/utils/sc_test.hpp
- sc-memory/test/CMakeLists.txt
- sc-memory/test/wrap/test_wrap.cpp
- sc-memory/test/wrap/units/test_codegen.cpp
- sc-memory/test/wrap/units/test_common.cpp
- sc-memory/test/wrap/units/test_event.cpp
- sc-memory/test/wrap/units/test_iterators.cpp
- sc-memory/test/wrap/units/test_sc_agent.cpp
- sc-memory/test/wrap/units/test_streams.cpp
- sc-memory/test/wrap/units/test_struct.cpp
- sc-memory/test/wrap/units/test_templates.cpp
- sc-memory/test/wrap/units/test_threading.cpp
- sc-memory/test/wrap/units/test_wait.cpp
> Unit test system improvements

- docs/changelog.md
- sc-memory/cpp/sc_debug.hpp
- sc-memory/cpp/sc_template.cpp
- sc-memory/cpp/sc_template.hpp
- sc-memory/cpp/sc_template_search.cpp
- sc-memory/cpp/sc_types.cpp
- sc-memory/cpp/sc_types.hpp
- sc-memory/test/wrap/units/test_templates.cpp
> Some issue fixing

- docs/changelog.md
- sc-memory/cpp/sc_struct.cpp
- sc-memory/cpp/sc_struct.hpp
- sc-memory/cpp/sc_template.hpp
> [cpp] Add ScSet class, ScStruct override it

- docs/changelog.md
- docs/python/python.md
- sc-kpm/python/_definitions/sc.py
- sc-kpm/python/sc_test.py
- sc-memory/cpp/python/sc_python_module.cpp
- tools/builder/CMakeLists.txt
- tools/builder/src/builder.cpp
> Some python improvements

- docs/cpp/kpm.md
- docs/cpp/templates.md
- docs/images/sc-events/sc-event-output-edge.gwf
- docs/other/scs.md
> [docs] Use vector SCg where it possible

- README.md
> Fixed old link in README

- docs/changelog.md
- sc-memory/cpp/sc_addr.hpp
- sc-memory/cpp/sc_memory.cpp
- sc-memory/cpp/sc_memory.hpp
- sc-memory/cpp/sc_template_gen.cpp
- sc-memory/cpp/sc_template_search.cpp
- sc-memory/sc-store/sc_event.c
- sc-memory/sc-store/sc_event/sc_event_private.h
- sc-memory/sc-store/sc_storage.c
- sc-memory/sc-store/sc_storage.h
- sc-memory/sc_helper.c
- sc-memory/sc_helper.h
- sc-memory/sc_memory.c
- sc-memory/sc_memory.h
- sc-memory/sc_memory_private.h
- sc-memory/test/wrap/units/test_event.cpp
- sc-memory/test/wrap/units/test_templates.cpp
- sc-network/sctp_server/sctpCommand.cpp
> Fix template search. Pending events support

- docs/changelog.md
- sc-memory/sc-core/sc_memory_version.c
> Bump version to 0.7.0

- scripts/install_deps_ubuntu.sh
> Add pip3 installation for Ubuntu

- docs/build/osx-build.md
> Small typo has been fixed

- tools/builder/src/builder.cpp
> Allow build from file with source folders list

- .gitignore
> Add folders of Clion to .gitignore

- .travis.yml
- sc-network/CMakeLists.txt
- sc-network/sctp_client/CMakeLists.txt
- sc-network/sctp_client/sctpClient.cpp
- sc-network/sctp_client/sctpClient.hpp
- sc-network/sctp_client/sctpTypes.hpp
- sc-network/sctp_server/CMakeLists.txt
- sc-network/sctp_server/main.cpp
- sc-network/sctp_server/sctpCommand.cpp
- sc-network/sctp_server/sctpEventManager.cpp
- sc-network/sctp_server/sctpServer.cpp
- sc-network/sctp_server/sctpServer.h
- sc-network/sctp_server/sctpStatistic.cpp
- scripts/install_deps_ubuntu.sh
- scripts/travis/install-tests.sh
> Fix sctp-server build

- CMakeLists.txt
- README.md
- cmake/FindLibClang.cmake
- sc-memory/CMakeLists.txt
- sc-memory/sc-core/sc-store/sc_storage.c
- scripts/install_deps_ubuntu.sh
> [cmake] Support Ubuntu 20.04

- sc-memory/sc-memory/python/sc_python_threads.hpp
> [sc-memory] Fix typo

- README.md
> Add Mint-specific instructions

- docs/changelog.md
- sc-memory/sc-memory/sc_keynodes.cpp
- sc-memory/sc-memory/sc_struct.cpp
- sc-memory/sc-memory/sc_struct.hpp
- sc-memory/tests/sc-memory/common/sc-struct.cpp
- sc-memory/tests/sc-memory/templates/sc-templates-build.cpp
- sc-memory/tests/sc-memory/templates/sc-templates-common.cpp
- sc-memory/tests/sc-memory/templates/sc-templates-regression.cpp
- sc-memory/tests/sc-memory/templates/sc-templates-search.cpp
- sc-memory/tests/sc-memory/templates/sc-templates-struct.cpp
Resolves: #319 
**Note**: Merge after #320
> [sc-memory] Replace context pointer with reference in ScSet

- docs/changelog.md
- sc-memory/sc-core/sc-store/sc_storage.c
- sc-memory/tests/sc-memory/common/sc-link.cpp
> Add a link content check before removing it from storage

- CMakeLists.txt
- docs/changelog.md
> [cmake] Set bin path to root of sc-machine(#352)

- docs/changelog.md
- sc-memory/sc-memory/scs/scs.g4
- sc-memory/sc-memory/scs/scs_parser.cpp
- sc-memory/sc-memory/scs/scs_parser.hpp
- sc-memory/tests/sc-memory/scs/scs-helper.cpp
- sc-memory/tests/sc-memory/scs/scs-regression.cpp
- sc-memory/tests/sc-memory/scs/scs_test_utils.hpp
- sc-memory/tests/scs/units/test_scs_alias.cpp
- sc-memory/tests/scs/units/test_scs_common.cpp
- sc-memory/tests/scs/units/test_scs_level_1.cpp
- sc-memory/tests/scs/units/test_scs_level_2.cpp
- sc-memory/tests/scs/units/test_scs_level_3.cpp
- sc-memory/tests/scs/units/test_scs_level_4.cpp
- sc-memory/tests/scs/units/test_scs_level_5.cpp
- sc-memory/tests/scs/units/test_scs_level_6.cpp
- sc-memory/tests/scs/units/test_scs_regression.cpp
> Fix issue with specifying type of elements inside contour

- docs/changelog.md
- sc-memory/sc-memory/sc_scs_helper.cpp
- sc-memory/sc-memory/scs/scs.g4
- sc-memory/tests/sc-memory/scs/scs-helper.cpp
- sc-memory/tests/scs/units/test_scs_alias.cpp
- sc-memory/tests/scs/units/test_scs_level_2.cpp
> [sc-memory][scs] Fix alias assignment issues (#350, #333)

- .gitmodules
- CMakeLists.txt
- README.md
- docs/changelog.md
- sc-memory/CMakeLists.txt
- sc-memory/sc-core/sc_memory.c
- sc-memory/sc-memory/CMakeLists.txt
- sc-memory/sc-memory/python/sc_python_interp.cpp
- sc-memory/sc-memory/sc_memory.cpp
- sc-memory/sc-memory/sc_memory.hpp
- sc-memory/sc-memory/sc_template.hpp
- sc-memory/tests/sc-memory/performance/main.cpp
- sc-memory/tests/sc-memory/performance/memory_create_edge.hpp
- sc-memory/tests/sc-memory/performance/memory_create_link.hpp
- sc-memory/tests/sc-memory/performance/memory_create_node.hpp
- sc-memory/tests/sc-memory/performance/memory_delete_elements.hpp
- sc-memory/tests/sc-memory/performance/memory_test.hpp
- sc-memory/tests/sc-memory/performance/perf.cmake
- sc-memory/tests/sc-memory/performance/sc_code_base_vs_extend.hpp
- sc-memory/tests/sc-memory/performance/template_search_complex.hpp
- sc-memory/tests/sc-memory/performance/template_search_smoke.hpp
- sc-memory/tests/sc-memory/performance/template_test.hpp
- sc-memory/tests/sc-memory/python/sc-python.cpp
- sc-memory/tests/sc-memory/tests.cmake
- scripts/travis/install-tests.sh
- thirdparty/CMakeLists.txt
- thirdparty/benchmark.cmake
- tools/builder/CMakeLists.txt
> Implement benchmarks

- .github/workflows/main.yml
- docs/dev/pr.md
> Add github actions

- CMakeLists.txt
- README.md
- scripts/install_deps_osx.sh
- tools/builder/CMakeLists.txt
> [cmake][doc] Fix build on OSX

- docs/changelog.md
- sc-memory/sc-core/sc-store/sc_storage.c
- sc-memory/sc-memory/sc_link.hpp
- sc-memory/sc-memory/sc_memory.cpp
- sc-memory/tests/sc-memory/common/sc-link.cpp
> Fix empty link content assignment

- CMakeLists.txt
- cmake/FindLibClang.cmake
- docs/changelog.md
- sc-memory/sc-core/sc-store/sc_element.h
- sc-memory/sc-core/sc-store/sc_event/sc_event_private.h
- sc-memory/sc-core/sc-store/sc_event/sc_event_queue.c
- sc-memory/tests/sc-memory/performance/main.cpp
- sc-network/sctp_client/sctpClient.hpp
- scripts/ci/install-deps.sh
> [cmake][sc-memory] Support arm64 on OSX
